name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Build
        run: pnpm run build
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Build
        run: pnpm run build
      - name: Lint
        run: pnpm run lint
  style:
    name: Check style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Build
        run: pnpm run build
      - name: Check style
        run: pnpm run style
  publish:
    name: Release

    runs-on: ubuntu-latest

    if: ${{ github.ref  == 'refs/heads/main' }}

    needs: [build, lint, style]

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance

    steps:
      - name: Create release
        id: release
        uses: googleapis/release-please-action@v5
      - name: Checkout release
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v7
      - name: Setup pnpm
        if: ${{ steps.release.outputs.release_created }}
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm run build
      - name: Publish package
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish --provenance --access public
